[project]
name = "scrapingpijamas"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bs4>=0.0.2",
    "django>=5.2.4",
    "requests>=2.32.4",
    "selenium>=4.34.2",
    "typing>=3.10.0.0",
]
