# Generated by Django 5.2.4 on 2025-08-13 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_loja', models.CharField(max_length=30)),
                ('nome_produto', models.CharField(max_length=100)),
                ('preco_produto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('url_produto', models.URLField()),
                ('url_foto', models.URLField()),
                ('status_ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
